USE [ProjectMgmt]
GO

-- this code was generated by script 19, drop the table and constraints manually first

 
CREATE TABLE [dbo].[TagToData](
	[TagId] [int] NOT NULL,
DatabaseContainerId int null,
DatabaseId int null,
DatabaseTypeId int null,
DatasetId int null,
FileGroupId int null,
FileId int null,
ProjectId int null,
SourceId int null,
LinkId int null,
CONSTRAINT [PK_TagToData] PRIMARY KEY CLUSTERED 
(
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
 
GO
 
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_Tags] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tags] ([TagId])
ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_Tags]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_DatabaseContainer_DatabaseContainerId]  FOREIGN KEY([DatabaseContainerId]) references [dbo].[DatabaseContainer](DatabaseContainerId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_DatabaseContainer_DatabaseContainerId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_Databases_DatabaseId]  FOREIGN KEY([DatabaseId]) references [dbo].[Databases](DatabaseId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_Databases_DatabaseId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_DatabaseTypeLookup_DatabaseTypeId]  FOREIGN KEY([DatabaseTypeId]) references [dbo].[DatabaseTypeLookup](DatabaseTypeId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_DatabaseTypeLookup_DatabaseTypeId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_Datasets_DatasetId]  FOREIGN KEY([DatasetId]) references [dbo].[Datasets](DatasetId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_Datasets_DatasetId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_FileGroups_FileGroupId]  FOREIGN KEY([FileGroupId]) references [dbo].[FileGroups](FileGroupId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_FileGroups_FileGroupId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_Files_FileId]  FOREIGN KEY([FileId]) references [dbo].[Files](FileId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_Files_FileId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_Projects_ProjectId]  FOREIGN KEY([ProjectId]) references [dbo].[Projects](ProjectId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_Projects_ProjectId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_FileSources_SourceId]  FOREIGN KEY([SourceId]) references [dbo].[FileSources](SourceId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_FileSources_SourceId]
ALTER TABLE [dbo].[TagToData]  WITH CHECK ADD  CONSTRAINT [FK_TagToData_WebLinks_LinkId]  FOREIGN KEY([LinkId]) references [dbo].[WebLinks](LinkId)
 ALTER TABLE [dbo].[TagToData] CHECK CONSTRAINT [FK_TagToData_WebLinks_LinkId]
 
GO
 
  ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_DatabaseContainer_DatabaseContainerId] unique (TagId,DatabaseContainerId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_Databases_DatabaseId] unique (TagId,DatabaseId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_DatabaseTypeLookup_DatabaseTypeId] unique (TagId,DatabaseTypeId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_Datasets_DatasetId] unique (TagId,DatasetId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_FileGroups_FileGroupId] unique (TagId,FileGroupId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_Files_FileId] unique (TagId,FileId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_Projects_ProjectId] unique (TagId,ProjectId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_FileSources_SourceId] unique (TagId,SourceId)
 ALTER TABLE [dbo].[TagToData] add constraint [UN_TagId_WebLinks_LinkId] unique (TagId,LinkId)
 
GO
 